<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-11-28T08:47:06+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.access_entity_updated
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'concrete5 local',
    'version_installed' => '5.7.5.9',
    'misc' => array(
        'access_entity_updated' => 1480319226,
    ),
);
